language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3.1

services: redis

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - RAILS_VERSION=4.2.7
      RDF_VERSION=1.99.1
    - RAILS_VERSION=5.0.0
      RDF_VERSION=2.1.1
notifications:
  irc:
    channels:
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
before_script:
  - jdk_switcher use oraclejdk8
